-- NBA Standings Prediction Pool (used by /sports/nba-standings).
-- Run this in the Supabase SQL editor before using the page.
--
-- One row per (season, participant): picks are stored as JSONB so the schema
-- never changes between seasons — a new season is just new rows with a new
-- season_key ("2026-27", "2027-28", …). Scoring lives in app code
-- (lib/sports/nbaStandingsPicks.ts) against whatever live standings the
-- season eventually provides.

create table if not exists public.nba_standings_predictions (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  season_key text not null,
  participant text not null,
  picks jsonb null,
  constraint nba_standings_predictions_pkey primary key (id),
  constraint nba_standings_predictions_season_participant_key
    unique (season_key, participant),
  constraint nba_standings_predictions_participant_check check (
    participant in ('Owen', 'Jacob', 'Ben', 'Eli', 'Oliver', 'Ronan', 'Alejandro')
  )
);

create index if not exists nba_standings_predictions_season_idx
  on public.nba_standings_predictions (season_key);

alter table public.nba_standings_predictions enable row level security;

grant select, insert, update on table public.nba_standings_predictions to anon, authenticated;

-- Prototype-only policies, matching the boardgames/sightings tables above.
drop policy if exists "prototype nba predictions are readable" on public.nba_standings_predictions;
drop policy if exists "prototype nba predictions are insertable" on public.nba_standings_predictions;
drop policy if exists "prototype nba predictions are editable" on public.nba_standings_predictions;

create policy "prototype nba predictions are readable"
  on public.nba_standings_predictions for select
  to anon, authenticated
  using (true);

create policy "prototype nba predictions are insertable"
  on public.nba_standings_predictions for insert
  to anon, authenticated
  with check (true);

create policy "prototype nba predictions are editable"
  on public.nba_standings_predictions for update
  to anon, authenticated
  using (true)
  with check (true);
