-- Board-game table used by /db-management.
-- Run this in the Supabase SQL editor before using the prototype page.

create table if not exists public.boardgames (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name text null default '',
  tier text null default 'Unranked',
  description text null,
  house_rules text null,
  quick_notes text null,
  full_rules text null,
  constraint boardgames_pkey primary key (id)
);

alter table public.boardgames enable row level security;

-- The public browser client uses the anon role when no user is signed in.
-- Authenticated sessions use the authenticated role. These grants are needed
-- in addition to RLS policies for PostgREST table access.
grant select, insert, update, delete on table public.boardgames to anon, authenticated;

do $$
declare
  identity_sequence regclass;
begin
  identity_sequence := pg_get_serial_sequence('public.boardgames', 'id');

  if identity_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to anon, authenticated',
      identity_sequence
    );
  end if;
end
$$;

-- Prototype-only policies. Replace these with authenticated, owner-scoped
-- policies before production use; the page itself displays a warning.
drop policy if exists "prototype board games are readable" on public.boardgames;
drop policy if exists "prototype board games are insertable" on public.boardgames;
drop policy if exists "prototype board games are editable" on public.boardgames;
drop policy if exists "prototype board games are removable" on public.boardgames;

create policy "prototype board games are readable"
  on public.boardgames for select
  to anon, authenticated
  using (true);

create policy "prototype board games are insertable"
  on public.boardgames for insert
  to anon, authenticated
  with check (true);

create policy "prototype board games are editable"
  on public.boardgames for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "prototype board games are removable"
  on public.boardgames for delete
  to anon, authenticated
  using (true);

-- Sighting uploads used by /conservation (Field Watch).
-- Run this in the Supabase SQL editor before using the upload feature.

create table if not exists public.sightings (
  id text primary key,
  created_at timestamptz not null default now(),
  species text not null default '',
  category text not null default 'other',
  location text not null default '',
  lat double precision not null default 0,
  lng double precision not null default 0,
  date text not null default '',
  observer text not null default '',
  note text not null default '',
  photo text not null default '' -- public URL of the compressed JPEG in the sightings-photos bucket
);

alter table public.sightings enable row level security;

grant select, insert, update, delete on table public.sightings to anon, authenticated;

-- Prototype-only policies, matching the boardgames table above.
drop policy if exists "prototype sightings are readable" on public.sightings;
drop policy if exists "prototype sightings are insertable" on public.sightings;
drop policy if exists "prototype sightings are editable" on public.sightings;
drop policy if exists "prototype sightings are removable" on public.sightings;

create policy "prototype sightings are readable"
  on public.sightings for select
  to anon, authenticated
  using (true);

-- May be security risk maybe in the future consider removing insert for anon
create policy "prototype sightings are insertable"
  on public.sightings for insert
  to anon, authenticated
  with check (true);

create policy "prototype sightings are editable"
  on public.sightings for update
  to authenticated
  using (true)
  with check (true);

create policy "prototype sightings are removable"
  on public.sightings for delete
  to authenticated
  using (true);

-- Upload photos live in a public Storage bucket. The client compresses each
-- photo to a <=512KB JPEG before uploading, so even thousands of sightings
-- stay far below the free tier. Public bucket + random filenames is fine for
-- the friends-only prototype; use a private bucket with signed URLs later.

insert into storage.buckets (id, name, public)
values ('sightings-photos', 'sightings-photos', true)
on conflict (id) do nothing;

-- Prototype-only policies, matching the sightings table above.
drop policy if exists "prototype sighting photos are readable" on storage.objects;
drop policy if exists "prototype sighting photos are uploadable" on storage.objects;

grant insert, select, update, delete on table storage.objects to anon, authenticated;

create policy "prototype sighting photos are readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'sightings-photos');

create policy "prototype sighting photos are uploadable"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'sightings-photos');
