-- Board-game tables used by /board-games and /db-management.
-- Run this in the Supabase SQL editor before using the prototype pages.

create table if not exists public.boardgames (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name text null default '',
  tier text null default 'Unranked',
  description text null,
  house_rules text null,
  quick_notes text null,
  full_rules text null,
  game_type text null default 'FFA',
  constraint boardgames_pkey primary key (id),
  constraint boardgames_game_type_check check (game_type in ('FFA', 'Team vs Team', 'Coop', 'PvPvE'))
);

-- Existing databases need the new metadata column added without losing rows.
alter table public.boardgames
  add column if not exists game_type text null default 'FFA';

do $$
begin
  alter table public.boardgames
    drop constraint if exists boardgames_game_type_check;
end
$$;

update public.boardgames
set game_type = 'PvPvE'
where game_type = 'PvPve';

update public.boardgames
set game_type = 'FFA'
where game_type is null or game_type not in ('FFA', 'Team vs Team', 'Coop', 'PvPvE');

alter table public.boardgames
  add constraint boardgames_game_type_check
  check (game_type in ('FFA', 'Team vs Team', 'Coop', 'PvPvE'));

create table if not exists public.players (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name text null,
  constraint players_pkey primary key (id)
);

-- Temporary compatibility table. Existing scores are converted into sessions
-- below, then this denormalized table is removed.
create table if not exists public.game_leaderboard (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  board_game_id bigint not null,
  name text not null,
  wins integer not null default 0,
  constraint game_leaderboard_pkey primary key (id),
  constraint game_leaderboard_game_name_key unique (board_game_id, name),
  constraint game_leaderboard_board_game_id_fkey
    foreign key (board_game_id) references public.boardgames(id) on delete cascade,
  constraint game_leaderboard_wins_check check (wins >= 0)
);

-- The pasted context called this table "game sessions". PostgreSQL allows that
-- only when quoted, so the app uses the conventional game_sessions identifier.
do $$
begin
  if to_regclass('public."game sessions"') is not null
    and to_regclass('public.game_sessions') is null then
    alter table public."game sessions" rename to game_sessions;
  end if;
end
$$;

create table if not exists public.game_sessions (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  board_game_id bigint not null,
  played_at timestamptz not null default now(),
  constraint game_sessions_pkey primary key (id),
  constraint game_sessions_board_game_id_fkey
    foreign key (board_game_id) references public.boardgames(id) on delete cascade
);

create table if not exists public.session_participants (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  session_id bigint not null,
  player_id bigint not null,
  is_winner boolean not null default false,
  constraint session_participants_pkey primary key (id),
  constraint session_participants_session_player_key unique (session_id, player_id),
  constraint session_participants_session_id_fkey
    foreign key (session_id) references public.game_sessions(id) on delete cascade,
  constraint session_participants_player_id_fkey
    foreign key (player_id) references public.players(id) on delete cascade
);

-- Existing databases may have created this table before the unique constraint
-- was added. Merge duplicates first, then add the constraint idempotently so
-- the later player-deduplication migration can safely use ON CONFLICT.
update public.session_participants as target
set is_winner = true
from public.session_participants as source
where target.session_id = source.session_id
  and target.player_id = source.player_id
  and source.is_winner = true
  and target.is_winner = false;

with duplicate_participants as (
  select
    id,
    row_number() over (
      partition by session_id, player_id
      order by id asc
    ) as row_number
  from public.session_participants
)
delete from public.session_participants as participants
using duplicate_participants
where participants.id = duplicate_participants.id
  and duplicate_participants.row_number > 1;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.session_participants'::regclass
      and conname = 'session_participants_session_player_key'
  ) then
    alter table public.session_participants
      add constraint session_participants_session_player_key
      unique (session_id, player_id);
  end if;
end
$$;

-- Import names from the old leaderboard table into the shared player list.
insert into public.players (name)
select legacy.name
from (
  select distinct on (lower(btrim(name))) btrim(name) as name
  from public.game_leaderboard
  where name is not null and btrim(name) <> ''
  order by lower(btrim(name)), wins desc, id asc
) as legacy
where not exists (
  select 1
  from public.players
  where lower(btrim(players.name)) = lower(legacy.name)
);

-- Merge case/spacing duplicate players without losing participant history.
with ranked_players as (
  select
    id,
    first_value(id) over (
      partition by lower(btrim(name))
      order by id asc
    ) as canonical_id,
    row_number() over (
      partition by lower(btrim(name))
      order by id asc
    ) as row_number
  from public.players
  where name is not null
), duplicate_players as (
  select id, canonical_id from ranked_players where row_number > 1
)
insert into public.session_participants (session_id, player_id, is_winner)
select
  participants.session_id,
  duplicate_players.canonical_id,
  bool_or(participants.is_winner)
from duplicate_players
join public.session_participants as participants
  on participants.player_id = duplicate_players.id
group by participants.session_id, duplicate_players.canonical_id
on conflict (session_id, player_id) do update
set is_winner = public.session_participants.is_winner or excluded.is_winner;

with ranked_players as (
  select
    id,
    row_number() over (
      partition by lower(btrim(name))
      order by id asc
    ) as row_number
  from public.players
  where name is not null
), duplicate_players as (
  select id from ranked_players where row_number > 1
)
delete from public.session_participants as participants
using duplicate_players
where participants.player_id = duplicate_players.id;

with ranked_players as (
  select
    id,
    row_number() over (
      partition by lower(btrim(name))
      order by id asc
    ) as row_number
  from public.players
  where name is not null
), duplicate_players as (
  select id from ranked_players where row_number > 1
)
delete from public.players as players
using duplicate_players
where players.id = duplicate_players.id;

update public.players
set name = btrim(name)
where name <> btrim(name);

create unique index if not exists players_normalized_name_key
  on public.players (lower(btrim(name)));

-- Remove the old function before dropping the table it returned.
drop function if exists public.add_player_to_all_leaderboards(bigint, text);

-- Convert old manually edited scores into real win sessions. Existing session
-- wins are preserved; only the missing difference is materialized.
create table if not exists public.scorebook_migrations (
  key text primary key,
  applied_at timestamptz not null default now()
);

do $$
declare
  legacy_entry record;
  new_session_id bigint;
  counter integer;
begin
  if not exists (
    select 1 from public.scorebook_migrations where key = 'leaderboard-to-sessions'
  ) then
    for legacy_entry in
      select
        legacy_scores.board_game_id,
        players.id as player_id,
        greatest(
          legacy_scores.legacy_wins - coalesce(existing_wins.win_count, 0),
          0
        )::integer as missing_wins
      from (
        select
          board_game_id,
          lower(btrim(name)) as normalized_name,
          sum(wins)::integer as legacy_wins
        from public.game_leaderboard
        group by board_game_id, lower(btrim(name))
      ) as legacy_scores
      join public.players
        on lower(btrim(players.name)) = legacy_scores.normalized_name
      left join (
        select
          sessions.board_game_id,
          participants.player_id,
          count(*)::integer as win_count
        from public.game_sessions as sessions
        join public.session_participants as participants
          on participants.session_id = sessions.id
        where participants.is_winner = true
        group by sessions.board_game_id, participants.player_id
      ) as existing_wins
        on existing_wins.board_game_id = legacy_scores.board_game_id
        and existing_wins.player_id = players.id
      where legacy_scores.legacy_wins > coalesce(existing_wins.win_count, 0)
    loop
      for counter in 1..legacy_entry.missing_wins loop
        insert into public.game_sessions (board_game_id)
        values (legacy_entry.board_game_id)
        returning id into new_session_id;

        insert into public.session_participants (session_id, player_id, is_winner)
        values (new_session_id, legacy_entry.player_id, true);
      end loop;
    end loop;

    insert into public.scorebook_migrations (key)
    values ('leaderboard-to-sessions');
  end if;
end;
$$;

-- Remove old policies/table after its migration has completed.
drop policy if exists "prototype leaderboard is readable" on public.game_leaderboard;
drop policy if exists "prototype leaderboard is insertable" on public.game_leaderboard;
drop policy if exists "prototype leaderboard is editable" on public.game_leaderboard;
drop policy if exists "prototype leaderboard is removable" on public.game_leaderboard;
drop table if exists public.game_leaderboard;

-- Every shared player appears for every game, including players with zero wins.
drop view if exists public.game_leaderboard_view;
create view public.game_leaderboard_view as
select
  games.id as board_game_id,
  players.id as player_id,
  players.name,
  count(winners.id)::integer as wins
from public.boardgames as games
cross join public.players
left join public.game_sessions as sessions
  on sessions.board_game_id = games.id
left join public.session_participants as winners
  on winners.session_id = sessions.id
  and winners.player_id = players.id
  and winners.is_winner = true
where players.name is not null
  and btrim(players.name) <> ''
group by games.id, players.id, players.name;

-- Remove triggers/functions from the old propagation approach.
drop trigger if exists seed_new_game_leaderboard on public.boardgames;
drop trigger if exists seed_player_leaderboards on public.players;
drop function if exists public.seed_new_game_leaderboard();
drop function if exists public.seed_player_leaderboards();
create or replace function public.add_player(p_name text)
returns table (id bigint, name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_name text := btrim(p_name);
begin
  if p_name is null or normalized_name = '' then
    raise exception 'Player name cannot be empty';
  end if;

  insert into public.players (name)
  values (normalized_name)
  on conflict do nothing;

  return query
  select players.id, players.name
  from public.players
  where lower(btrim(players.name)) = lower(normalized_name)
  order by players.id
  limit 1;
end;
$$;

create or replace function public.record_player_win(
  p_board_game_id bigint,
  p_player_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  new_session_id bigint;
begin
  if not exists (select 1 from public.boardgames where id = p_board_game_id) then
    raise exception 'The requested board game does not exist';
  end if;
  if not exists (select 1 from public.players where id = p_player_id) then
    raise exception 'The requested player does not exist';
  end if;

  insert into public.game_sessions (board_game_id)
  values (p_board_game_id)
  returning id into new_session_id;

  insert into public.session_participants (session_id, player_id, is_winner)
  values (new_session_id, p_player_id, true);
end;
$$;

create or replace function public.remove_player_win(
  p_board_game_id bigint,
  p_player_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  session_to_remove bigint;
begin
  select sessions.id
  into session_to_remove
  from public.game_sessions as sessions
  join public.session_participants as participants
    on participants.session_id = sessions.id
  where sessions.board_game_id = p_board_game_id
    and participants.player_id = p_player_id
    and participants.is_winner = true
  order by sessions.played_at desc, sessions.id desc
  limit 1;

  if session_to_remove is null then
    raise exception 'No recorded win exists for this player and game';
  end if;

  delete from public.session_participants
  where session_id = session_to_remove
    and player_id = p_player_id
    and is_winner = true;

  delete from public.game_sessions
  where id = session_to_remove
    and not exists (
      select 1 from public.session_participants
      where session_id = session_to_remove
    );
end;
$$;

alter table public.boardgames enable row level security;
alter table public.players enable row level security;
alter table public.game_sessions enable row level security;
alter table public.session_participants enable row level security;

grant select, insert, update, delete on table public.boardgames to anon, authenticated;
grant select, insert, update, delete on table public.players to anon, authenticated;
grant select on table public.game_leaderboard_view to anon, authenticated;
grant execute on function public.add_player(text) to anon, authenticated;
grant execute on function public.record_player_win(bigint, bigint) to anon, authenticated;
grant execute on function public.remove_player_win(bigint, bigint) to anon, authenticated;
grant select, insert, update, delete on table public.game_sessions to anon, authenticated;
grant select, insert, update, delete on table public.session_participants to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Prototype-only policies. Replace these with authenticated, owner-scoped
-- policies before production use; the page itself displays a warning.
drop policy if exists "prototype board games are readable" on public.boardgames;
drop policy if exists "prototype board games are insertable" on public.boardgames;
drop policy if exists "prototype board games are editable" on public.boardgames;
drop policy if exists "prototype board games are removable" on public.boardgames;

create policy "prototype board games are readable"
  on public.boardgames for select to anon, authenticated using (true);
create policy "prototype board games are insertable"
  on public.boardgames for insert to anon, authenticated with check (true);
create policy "prototype board games are editable"
  on public.boardgames for update to anon, authenticated using (true) with check (true);
create policy "prototype board games are removable"
  on public.boardgames for delete
  to anon, authenticated
  using (true);

-- Sighting uploads used by /conservation (Field Watch).
-- Run this in the Supabase SQL editor before using the upload feature.

create table if not exists public.sightings (
  id text primary key,
  created_at timestamptz not null default now(),
  species text not null default '',
  category text not null default 'other',
  location text not null default '',
  lat double precision not null default 0,
  lng double precision not null default 0,
  date text not null default '',
  observer text not null default '',
  note text not null default '',
  photo text not null default '' -- public URL of the compressed JPEG in the sightings-photos bucket
);

alter table public.sightings enable row level security;

grant select, insert, update, delete on table public.sightings to anon, authenticated;

-- Prototype-only policies, matching the boardgames table above.
drop policy if exists "prototype sightings are readable" on public.sightings;
drop policy if exists "prototype sightings are insertable" on public.sightings;
drop policy if exists "prototype sightings are editable" on public.sightings;
drop policy if exists "prototype sightings are removable" on public.sightings;

create policy "prototype sightings are readable"
  on public.sightings for select
  to anon, authenticated
  using (true);

-- May be security risk maybe in the future consider removing insert for anon
create policy "prototype sightings are insertable"
  on public.sightings for insert
  to anon, authenticated
  with check (true);

create policy "prototype sightings are editable"
  on public.sightings for update
  to authenticated
  using (true)
  with check (true);

create policy "prototype sightings are removable"
  on public.sightings for delete
  to authenticated
  using (true);

-- Upload photos live in a public Storage bucket. The client compresses each
-- photo to a <=512KB JPEG before uploading, so even thousands of sightings
-- stay far below the free tier. Public bucket + random filenames is fine for
-- the friends-only prototype; use a private bucket with signed URLs later.

insert into storage.buckets (id, name, public)
values ('sightings-photos', 'sightings-photos', true)
on conflict (id) do nothing;

-- Prototype-only policies, matching the sightings table above.
drop policy if exists "prototype sighting photos are readable" on storage.objects;
drop policy if exists "prototype sighting photos are uploadable" on storage.objects;

grant insert, select, update, delete on table storage.objects to anon, authenticated;

create policy "prototype sighting photos are readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'sightings-photos');

create policy "prototype sighting photos are uploadable"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'sightings-photos');
  on public.boardgames for delete to anon, authenticated using (true);

drop policy if exists "prototype players are readable" on public.players;
drop policy if exists "prototype players are insertable" on public.players;
drop policy if exists "prototype players are editable" on public.players;
drop policy if exists "prototype players are removable" on public.players;

create policy "prototype players are readable"
  on public.players for select to anon, authenticated using (true);
create policy "prototype players are insertable"
  on public.players for insert to anon, authenticated with check (true);
create policy "prototype players are editable"
  on public.players for update to anon, authenticated using (true) with check (true);
create policy "prototype players are removable"
  on public.players for delete to anon, authenticated using (true);

drop policy if exists "prototype game sessions are readable" on public.game_sessions;
drop policy if exists "prototype game sessions are insertable" on public.game_sessions;
drop policy if exists "prototype game sessions are editable" on public.game_sessions;
drop policy if exists "prototype game sessions are removable" on public.game_sessions;

create policy "prototype game sessions are readable"
  on public.game_sessions for select to anon, authenticated using (true);
create policy "prototype game sessions are insertable"
  on public.game_sessions for insert to anon, authenticated with check (true);
create policy "prototype game sessions are editable"
  on public.game_sessions for update to anon, authenticated using (true) with check (true);
create policy "prototype game sessions are removable"
  on public.game_sessions for delete to anon, authenticated using (true);

drop policy if exists "prototype session participants are readable" on public.session_participants;
drop policy if exists "prototype session participants are insertable" on public.session_participants;
drop policy if exists "prototype session participants are editable" on public.session_participants;
drop policy if exists "prototype session participants are removable" on public.session_participants;

create policy "prototype session participants are readable"
  on public.session_participants for select to anon, authenticated using (true);
create policy "prototype session participants are insertable"
  on public.session_participants for insert to anon, authenticated with check (true);
create policy "prototype session participants are editable"
  on public.session_participants for update to anon, authenticated using (true) with check (true);
create policy "prototype session participants are removable"
  on public.session_participants for delete to anon, authenticated using (true);
