-- Board-game tables used by /board-games and /db-management.
-- Run this in the Supabase SQL editor before using the prototype pages.

create table if not exists public.boardgames (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name text null default '',
  tier text null default 'Unranked',
  description text null,
  house_rules text null,
  quick_notes text null,
  full_rules text null,
  constraint boardgames_pkey primary key (id)
);

create table if not exists public.players (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name text null,
  constraint players_pkey primary key (id)
);

-- The pasted context called this table "game sessions". PostgreSQL allows that
-- only when quoted, so the app uses the conventional game_sessions identifier.
-- Rename that quoted legacy table if it already exists, so rerunning this file
-- upgrades the database instead of creating a parallel scorebook.
do $$
begin
  if to_regclass('public."game sessions"') is not null
    and to_regclass('public.game_sessions') is null then
    alter table public."game sessions" rename to game_sessions;
  end if;
end
$$;

create table if not exists public.game_sessions (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  board_game_id bigint not null,
  played_at timestamptz not null default now(),
  constraint game_sessions_pkey primary key (id),
  constraint game_sessions_board_game_id_fkey
    foreign key (board_game_id) references public.boardgames(id) on delete cascade
);

create table if not exists public.session_participants (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  session_id bigint not null,
  player_id bigint not null,
  is_winner boolean not null default false,
  constraint session_participants_pkey primary key (id),
  constraint session_participants_session_player_key unique (session_id, player_id),
  constraint session_participants_session_id_fkey
    foreign key (session_id) references public.game_sessions(id) on delete cascade,
  constraint session_participants_player_id_fkey
    foreign key (player_id) references public.players(id) on delete cascade
);

alter table public.boardgames enable row level security;
alter table public.players enable row level security;
alter table public.game_sessions enable row level security;
alter table public.session_participants enable row level security;

grant select, insert, update, delete on table public.boardgames to anon, authenticated;
grant select, insert, update, delete on table public.players to anon, authenticated;
grant select, insert, update, delete on table public.game_sessions to anon, authenticated;
grant select, insert, update, delete on table public.session_participants to anon, authenticated;
-- Identity sequences on pre-existing tables also need explicit browser access.
-- This is intentionally broad for the prototype schema; scope it per owner in production.
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
declare
  identity_sequence regclass;
begin
  foreach identity_sequence in array array[
    pg_get_serial_sequence('public.boardgames', 'id'),
    pg_get_serial_sequence('public.players', 'id'),
    pg_get_serial_sequence('public.game_sessions', 'id'),
    pg_get_serial_sequence('public.session_participants', 'id')
  ] loop
    if identity_sequence is not null then
      execute format(
        'grant usage, select on sequence %s to anon, authenticated',
        identity_sequence
      );
    end if;
  end loop;
end
$$;

-- Prototype-only policies. Replace these with authenticated, owner-scoped
-- policies before production use; the page itself displays a warning.
drop policy if exists "prototype board games are readable" on public.boardgames;
drop policy if exists "prototype board games are insertable" on public.boardgames;
drop policy if exists "prototype board games are editable" on public.boardgames;
drop policy if exists "prototype board games are removable" on public.boardgames;

create policy "prototype board games are readable"
  on public.boardgames for select
  to anon, authenticated
  using (true);

create policy "prototype board games are insertable"
  on public.boardgames for insert
  to anon, authenticated
  with check (true);

create policy "prototype board games are editable"
  on public.boardgames for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "prototype board games are removable"
  on public.boardgames for delete
  to anon, authenticated
  using (true);

drop policy if exists "prototype players are readable" on public.players;
drop policy if exists "prototype players are insertable" on public.players;
drop policy if exists "prototype players are editable" on public.players;
drop policy if exists "prototype players are removable" on public.players;

create policy "prototype players are readable"
  on public.players for select
  to anon, authenticated
  using (true);

create policy "prototype players are insertable"
  on public.players for insert
  to anon, authenticated
  with check (true);

create policy "prototype players are editable"
  on public.players for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "prototype players are removable"
  on public.players for delete
  to anon, authenticated
  using (true);

drop policy if exists "prototype game sessions are readable" on public.game_sessions;
drop policy if exists "prototype game sessions are insertable" on public.game_sessions;
drop policy if exists "prototype game sessions are editable" on public.game_sessions;
drop policy if exists "prototype game sessions are removable" on public.game_sessions;

create policy "prototype game sessions are readable"
  on public.game_sessions for select
  to anon, authenticated
  using (true);

create policy "prototype game sessions are insertable"
  on public.game_sessions for insert
  to anon, authenticated
  with check (true);

create policy "prototype game sessions are editable"
  on public.game_sessions for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "prototype game sessions are removable"
  on public.game_sessions for delete
  to anon, authenticated
  using (true);

drop policy if exists "prototype session participants are readable" on public.session_participants;
drop policy if exists "prototype session participants are insertable" on public.session_participants;
drop policy if exists "prototype session participants are editable" on public.session_participants;
drop policy if exists "prototype session participants are removable" on public.session_participants;

create policy "prototype session participants are readable"
  on public.session_participants for select
  to anon, authenticated
  using (true);

create policy "prototype session participants are insertable"
  on public.session_participants for insert
  to anon, authenticated
  with check (true);

create policy "prototype session participants are editable"
  on public.session_participants for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "prototype session participants are removable"
  on public.session_participants for delete
  to anon, authenticated
  using (true);
