// lib/sports/pitchPredictor.test.ts
//
// Verifies the browser-side reimplementation of the xgboost v1 pitch model
// against probabilities computed by the real model in Python. The fixture is
// generated by notebooks/export_xgboost_for_web.py.
//
// Run with:  node --experimental-strip-types --test lib/sports/pitchPredictor.test.ts

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { predictProba, workloadBucket, type PitchModel } from "./pitchPredictor.ts";

function loadModel(): PitchModel {
  return JSON.parse(
    readFileSync(new URL("../../public/data/xgboost-pitch-model.json", import.meta.url), "utf8")
  ) as PitchModel;
}

function loadFixture(): { rows: { x: number[]; proba: number[] }[] } {
  return JSON.parse(
    readFileSync(new URL("../../notebooks/xgboost_v1_proba_fixture.json", import.meta.url), "utf8")
  );
}

test("predictProba matches Python predict_proba within 1e-4", () => {
  const model = loadModel();
  const fixture = loadFixture();

  let maxErr = 0;
  for (const row of fixture.rows) {
    const got = predictProba(model, row.x);
    for (let i = 0; i < row.proba.length; i++) {
      maxErr = Math.max(maxErr, Math.abs(got[i] - row.proba[i]));
    }
  }
  assert.ok(maxErr < 1e-4, `max error ${maxErr} exceeds 1e-4`);
});

test("probabilities are a valid distribution", () => {
  const model = loadModel();
  const fixture = loadFixture();
  const probs = predictProba(model, fixture.rows[0].x);
  const sum = probs.reduce((a, b) => a + b, 0);
  assert.ok(Math.abs(sum - 1) < 1e-9);
  assert.equal(probs.length, 12);
});

test("workloadBucket maps pitch counts to 5 buckets", () => {
  assert.equal(workloadBucket(0), 0);
  assert.equal(workloadBucket(20), 0);
  assert.equal(workloadBucket(21), 1);
  assert.equal(workloadBucket(60), 2);
  assert.equal(workloadBucket(81), 4);
  assert.equal(workloadBucket(150), 4);
});